export const UPDATE_ARTICLES = "UPDATE_ARTICLES"
export const UPDATE_USERS = "UPDATE_USERS"
export const UPDATE_PHOTOS = "UPDATE_PHOTOS"

export const CONTENT_LOADING = "CONTENT_LOADING"
export const CONTENT_LOADED = "CONTENT_LOADED"